before_script:
  - bash ci/docker_install.sh

test_5.4:
  image : phpplatform/php-apache-xdebug-composer:5.4
  script :
    - ./vendor/bin/phpunit -c ci/phpunit.xml

# test_7.1:
#  image : php:7.1-apache
#  script :
#    - ./vendor/bin/phpunit -c phpunit.xml

after_script:
  - bash <(curl -s https://codecov.io/bash) -t c09c03aa-44ab-4b07-934e-f20fd3a604c1
  - cat coverage.xml