before_script:
  - bash ci/docker_install.sh >/dev/null

test_5.6:
  image : php:5.6-apache
  script :
    - ./vendor/bin/phpunit -c phpunit.xml

# test_7.1:
#  image : php:7.1-apache
#  script :
#    - ./vendor/bin/phpunit -c phpunit.xml

after_script:
#  - bash <(curl -s https://codecov.io/bash)